import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import {BsSearch} from 'react-icons/bs'; 
import Weather from '../components/weather';
import Loader from '../components/Spinner';

export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);


  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
  // console.log(city);

  const fetchWeather = (e)=>{
    e.preventDefault();
    setLoading = (true);
    axios.get(url).then((response)=>{
      // console.log(response);
      setWeather(response.data);
    })
    setCity('');
    setLoading = (false);
  }



  if(loading){
    return <Loader/>
  }else{
    return (
      <div>
        <Head>
          <title>Weather app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* background */}
        <div className='absolute top-0 bottom-0 left-0 right-0 bg-black/40 z-[1]'/>
        {/* bg-image */}
         <Image src='https://images.unsplash.com/photo-1522441815192-d9f04eb0615c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzV8fGRhcmslMjBiZyUyMHdpdGglMjB0ZXh0dXJlJTIwYW5kJTIwYmR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60' layout='fill' className='objetc-cover'/>
        {/* search */}
        <div className='p-1'>
        <div className='relative flex justify-between items-center max-w-[500px] sm:max-w-[300px] w-full m-auto pt-4 text-white z-10'>
          <form onSubmit={fetchWeather}  className='flex justify-between items-center w-full p-3 m-auto bg-transparent border border-gray-300 text-white rounded-2xl shadow-2xl'>
            <div>
              <input className='bg-transparent border-none text-white focus:outline-none placeholder:italic placeholder:text-gray-300 ' type='text' placeholder='Search city' onChange={(e)=>setCity(e.target.value)}/>
            </div>
            <button onClick={fetchWeather}><BsSearch/></button>
          </form>
        </div>
        </div>
   
        {/* weather component */}
  
        {weather.main && <Weather data={weather}/>}
  
      </div>
    )
  }
  
}
